# Generated by Django 5.1.6 on 2025-03-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_challenge_challenge_type_alter_challenge_week_number_and_more'),
        ('web', '0024_create_success_story'),
    ]

    operations = [
    ]
