# Generated by Django 5.1.6 on 2025-03-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_alter_leaderboardentry_options_and_more'),
    ]

    operations = [
    ]
