# Generated by Django 5.1.6 on 2025-03-20 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_merged_leaderboard_migrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='user',
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reason', models.CharField(help_text='Reason for awarding points', max_length=255)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='web.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Points',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.DeleteModel(
            name='FriendLeaderboard',
        ),
        migrations.DeleteModel(
            name='LeaderboardEntry',
        ),
    ]
