# Generated by Django 5.1.6 on 2025-03-20 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_remove_leaderboardentry_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='point_type',
            field=models.CharField(choices=[('regular', 'Regular Points'), ('streak', 'Streak Points'), ('bonus', 'Bonus Points')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='points',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_awarded', to='web.challenge'),
        ),
    ]
